version: "3.8"
services:
  laravel:
    image: laravelfans/laravel:10.43.0
    depends_on:
      - db
    volumes:
      - ./:/var/www/laravel
    ports:
      - 8000:80
    env_file: .env

  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
